export const enum MondayColumnType {
    AUTO_NUMBER = 'auto_number',
    BUTTON = 'button',
    CHECKBOX = 'checkbox',
    COLOR_PICKER = 'color_picker',
    BOARD_RELATION = 'board_relation',
    COUNTRY = 'country',
    CREATION_LOG = 'creation_log',
    DATE = 'date',
    DEPENDENCY = 'dependency',
    DROPDOWN = 'dropdown',
    EMAIL = 'email',
    FILES = 'file',
    FORMULA = 'formula',
    HOUR = 'hour',
    ITEM_ID = 'item_id',
    LAST_UPDATED = 'last_updated',
    LINK = 'link',
    LOCATION = 'location',
    LONG_TEXT = 'long_text',
    MIRROR = 'mirror',
    DOC = 'doc',
    NAME = 'name',
    NUMBERS = 'numbers',
    PEOPLE = 'people',
    PHONE = 'phone',
    PROGRESS_TRACKING = 'progress',
    RATING = 'rating',
    STATUS = 'status',
    TAGS = 'tags',
    TEXT = 'text',
    TIMELINE = 'timeline',
    TIME_TRACKING = 'time_tracking',
    VOTE = 'vote',
    WEEK = 'week',
    WORLD_CLOCK = 'world_clock',
    SUBTASKS = 'subtasks',
    PROGRESS = 'progress',
    UNSUPPORTED = 'unsupported',
    ID = 'id',
}

export const MondayNotWritableColumnType = [
    MondayColumnType.UNSUPPORTED,
    MondayColumnType.AUTO_NUMBER,
    MondayColumnType.COLOR_PICKER,
    MondayColumnType.BUTTON,
    MondayColumnType.MIRROR,
    MondayColumnType.SUBTASKS,
    MondayColumnType.ITEM_ID,
    MondayColumnType.CREATION_LOG,
    MondayColumnType.FILES,
    MondayColumnType.FORMULA,
    MondayColumnType.DOC,
    MondayColumnType.LAST_UPDATED,
    MondayColumnType.PROGRESS,
    MondayColumnType.TAGS,
    MondayColumnType.TIME_TRACKING,
    MondayColumnType.VOTE,
    MondayColumnType.ID,
];

export const enum BoardKind {
    PRIVATE = 'private',
    PUBLIC = 'public',
    SHARE = 'share',
}

export const enum BoardState {
    ACTIVE = 'active',
    ALL = 'all',
    ARCHIVED = 'archived',
    DELETED = 'deleted',
}